boards/urls.py
from django.urls import path

from . import views

app_name = 'boards'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:post_id>/', views.detail, name='detail'),
    path('new_bid/<int:post_id>/', views.create_bid, name='create_bid'),
    path('new_post/', views.create_post, name='create_post'),
    path('my_posts/', views.my_posts, name='my_posts'),
    path('my_bids/', views.my_bids, name='my_bids'),
    path('winner_selected/<int:bid_id>/', views.set_winner_selected, name='winner_selected'),
    path('search/', views.search, name='search'),
    path('delete_post/<int:post_id>/', views.delete_post, name='delete_post'),
    path('delete_bid/<int:bid_id>/', views.delete_bid, name='delete_bid')
]

partywhip/urls.py
from django.contrib import admin
from django.contrib.auth.views import LogoutView, LoginView
from django.urls import path, include, re_path

from partywhip import views

urlpatterns = [
    path('', views.welcome, name="welcome"),
    path('admin/', admin.site.urls),
    path('boards/', include('boards.urls')),
    path('signup/', views.signup, name='signup'),
    path('login/', LoginView.as_view(template_name="partywhip/login_form.html"), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

boards/models.py
from datetime import timezone, datetime

from django.conf import settings
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db import models
from django.core.exceptions import NON_FIELD_ERRORS, ValidationError
from django.utils import timezone

from boards.date import Date


class Post(models.Model):
    user = models.CharField(max_length=200)
    title = models.CharField(max_length=200, blank=False, verbose_name="Post Title")
    pub_date = models.DateTimeField('Date Published')
    end_date = models.DateTimeField('Bidding Close Date')
    event_date = models.DateTimeField('Event Date')
    budget = models.IntegerField(blank=False, verbose_name="Maximum Budget")
    location = models.CharField(max_length=100, verbose_name="Location")
    comment = models.CharField(max_length=300, verbose_name="Bid Comments")
    winner_selected = models.BooleanField(default=False)
    status = models.CharField(max_length=10, default="OPEN")
    winning_bid = models.IntegerField(default=-1)

    def __str__(self):
        return self.title

    def clean_fields(self, exclude=None):
        super().clean_fields(exclude=exclude)

        end_date = Date(self.end_date.day, self.end_date.month, self.end_date.year)
        event_date = Date(self.event_date.day, self.event_date.month, self.event_date.year)
        curr_date = Date(timezone.now().day, timezone.now().month, timezone.now().year)

        if end_date.greaterThan(event_date):
            raise ValidationError("Invalid Date: the Event Date must be after the End Date")
        if not end_date.greaterThan(curr_date) or not event_date.greaterThan(curr_date):
            raise ValidationError("Invalid Date: the date you have chosen has passed")


class Bid(models.Model):
    user = models.CharField(max_length=200)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    price = models.IntegerField(blank=False, verbose_name="Bid Price")
    comment = models.CharField(max_length=300, verbose_name="Bid Comments")
    contact_details = models.CharField(max_length=300, verbose_name="Contact Details")

    def __str__(self):
        return str(self.price)

boards/forms.py
import datetime

from django.core.exceptions import ValidationError
from django.forms import ModelForm
from django import forms

from django.core.exceptions import ValidationError

from boards.models import Post, Bid

from django.utils import timezone


class DateInput(forms.DateInput):
    input_type = 'date'


class PostForm(ModelForm):
    class Meta:
        model = Post
        widgets = {
            'event_date': DateInput(),
            'end_date': DateInput(),
            'title': forms.TextInput(attrs={'placeholder': 'Enter a title'}),
            'budget': forms.TextInput(attrs={'placeholder': 'Enter your budget'}),
            'location': forms.TextInput(attrs={'placeholder':'Enter a suburb'}),
            'comment': forms.Textarea(attrs={'placeholder':'Extra information (e.g. number of guests, occasion, type of venue, cooking facilities)', 'style': 'height: 180px'}),

        }

        exclude = ('user', 'pub_date', 'winner_selected', 'status', 'winning_bid',)


class BidForm(ModelForm):
    class Meta:
        model = Bid
        widgets = {
            'price': forms.TextInput(attrs={'placeholder': 'Enter bid amount'}),
            'comment': forms.TextInput(attrs={'placeholder': 'Enter extra information'}),
            'contact_details': forms.TextInput(attrs={'placeholder': 'Enter contact details'})
        }
        exclude = ('user', 'post')


SORT_BY= [
    ('most_recent', 'Most Recent'),
    ('budget_ascending', 'Budget (Ascending)'),
    ('budget_descending', 'Budget (Descending)'),
    ('event_date_descending', 'Event Date (Descending)'),
    ('event_date_ascending', 'Event Date (Ascending)'),
    ('this_week', 'This Week'),
    ('this_month', 'This Month'),
    ]

def validate_positive(value):
    if value < 0:
        raise ValidationError('Enter positive Value')
    return value


class OptionsForm(forms.Form):
    sort_option = forms.ChoiceField(label = '', choices=SORT_BY, widget=forms.RadioSelect(attrs={'style' : 'margin-right: 10px'}), required=False)
    min_value = forms.FloatField(label = 'Min Budget', min_value=0, max_value=100000, required=False, validators=[validate_positive], widget=forms.TextInput(attrs={ 'class' : 'budgetRange'}))
    max_value = forms.FloatField(label = 'Max Budget', min_value=0, max_value=100000, required=False, validators=[validate_positive], widget=forms.TextInput(attrs={ 'class' : 'budgetRange'}))

boards/views.py
import datetime

from django import forms
from django.core.exceptions import ValidationError
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Q

# Create your views here.
from boards.forms import PostForm, BidForm, OptionsForm
from boards.models import Post, Bid
from boards.Sort import Sort


@login_required
def index(request):
    options_form = OptionsForm(data=request.POST)

    if not options_form.is_valid():
        options_form = OptionsForm()
        post_list = Post.objects.exclude(end_date__lte=timezone.localtime()).order_by('-pub_date')
    else:
        sort_by = request.GET.get('sort_option')
        min_value = request.GET.get('min_value')
        max_value = request.GET.get('max_value')

        if sort_by is not None and (min_value is not None or max_value is not None):
            options_form.add_error('sort_option', "Select one sorting mechanism")

        if min_value is not None and max_value is not None:
            if min_value is not "" and max_value is not "" and min_value > max_value:
                options_form.add_error('max_value', "Enter Valid Budget Range")

        if sort_by is not None:
            # DAFNY SORTS HERE
            sort = Sort()
            post_list = list(Post.objects.exclude(end_date__lte=timezone.localtime()))
            if sort_by == 'most_recent':
                sort.insertion_pub_date_descending(post_list)
            elif sort_by == 'budget_ascending':
                sort.cocktail_budget_ascending(post_list)
            elif sort_by == 'budget_descending':
                sort.bubble_budget_descending(post_list)
            elif sort_by == 'event_date_ascending':
                sort.selection_event_date_ascending(post_list)
            elif sort_by == 'event_date_descending':
                sort.insertion_event_date_descending(post_list)
            elif sort_by == 'this_week':
                today = datetime.datetime.now()
                week = datetime.timedelta(days=7)
                post_list = Post.objects.filter(event_date__lt=(today + week),
                                                    event_date__gte=datetime.datetime.now())
            elif sort_by == 'this_month':
                today = datetime.datetime.now()
                month = datetime.timedelta(days=30)
                post_list = Post.objects.filter(event_date__lt=(today + month),
                                                    event_date__gte=datetime.datetime.now())
            else:
                post_list = Post.objects.exclude(end_date__lte=timezone.localtime()).order_by('-pub_date')
        elif min_value is not None and min_value is not "" and max_value is not None and max_value is not "" and min_value < max_value:
            post_list = Post.objects.exclude(end_date__lte=timezone.localtime()).filter(budget__gte=min_value,
                                            budget__lte=max_value)
        elif min_value is not None and min_value is not "" and (max_value is None or max_value is ""):
            post_list = Post.objects.exclude(end_date__lte=timezone.localtime()).filter(budget__gte=min_value)
        elif max_value is not None and max_value is not "" and (min_value is None or min_value is ""):
            post_list = Post.objects.exclude(end_date__lte=timezone.localtime()).filter(budget__lte=max_value)
        else:
            post_list = Post.objects.exclude(end_date__lte=timezone.localtime()).order_by('-pub_date')

    context = {
        'post_list': post_list,
        'form': options_form
    }
    return render(request, 'boards/index.html', context)

@login_required
def detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)

    if post.end_date > timezone.localtime():
        post.status = "OPEN"
    elif post.end_date <= timezone.localtime():
        post.status = "CLOSED"
    if post.winner_selected == True:
        post.status = "ASSIGNED"
        
    post.save()
    context = {
        'post': post,
        'user': request.user
    }

    return render(request, 'boards/detail.html', context)

@login_required
def create_post(request):
    if request.method == "POST":
        # use this to add users to DB TABLE TODO
        post = Post(user=request.user, pub_date=timezone.localtime(), winner_selected=False, )
        form = PostForm(instance=post, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('boards:index')
    else:
        form = PostForm()
    return render(request, "boards/new_post_form.html", {'form': form})


@login_required
def create_bid(request, post_id):
    p = get_object_or_404(Post, pk=post_id)
    if request.method == "POST":
        bid = Bid(user=request.user, post=p)
        form = BidForm(instance=bid, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('boards:detail', post_id)
    else:
        form = BidForm()
    return render(request, "boards/new_bid_form.html", {'form': form, 'post_id': post_id})


@login_required
def my_posts(request):
    post_list = Post.objects.filter(user=request.user).order_by('-pub_date')

    return render(request, 'boards/my_posts.html', {'post_list': post_list})


@login_required
def my_bids(request):
    bid_list = Bid.objects.filter(user=request.user).order_by('-post__pub_date')
    return render(request, 'boards/my_bids.html', {'bid_list': bid_list})

@login_required
def search(request):
    search_query = request.GET.get('search_box', None)
    search_results = Post.objects.filter(Q(title__contains=search_query)|Q(location__contains=search_query))
    context = {
        'post_list': search_results,
        'search_term': search_query,
    }
    return render(request, 'boards/search.html', context)

@login_required
def set_winner_selected(request, bid_id):
    # print(bid_id)
    # for bid in Bid.objects.all():
    #     print(bid.id)
    b = get_object_or_404(Bid, pk=bid_id)
    b.post.winner_selected = True
    b.post.status = "ASSIGNED"
    b.post.winning_bid = b.id
    b.post.save()
    b.save()
    context = {
        'post': b.post,
        'bidder': b.id
    }
    return render(request, 'boards/winner_selected.html', context)

@login_required
def delete_post(request, post_id):
    post = Post.objects.get(pk=post_id)
    post.delete()

    post_list = Post.objects.filter(user=request.user).order_by('-pub_date')
    return render(request, 'boards/my_posts.html', {'post_list': post_list})

@login_required
def delete_bid(request, bid_id):
    bid = Bid.objects.get(pk=bid_id)
    bid.delete()

    bid_list = Bid.objects.filter(user=request.user).order_by('-post__pub_date')
    return render(request, 'boards/my_bids.html', {'bid_list': bid_list})

templates/boards/detail.html
{% extends 'base.html' %}

{% block title %}
{{ post.title }}
{% endblock %}

{% block content %}
{% if post.status == "CLOSED" %}
    <div align="center" class="alert alert-danger" role="alert">
        This post is {{ post.status }}
    </div>
{% endif %}

{% if post.status == "ASSIGNED" %}
    <div align="center" class="alert alert-danger" role="alert">
        This post has been {{ post.status }}
    </div>
{% endif %}
<div class="card bg-light mt-3">
    <div class="container p-5">
        <h1 align="center">{{ post.title }}</h1>
        <p align="center">Closing Date: {{ post.end_date.date }}</p>
        <div class="row">
            <div class="col-sm-10">
                <p><i id="icon" class="fas fa-user-circle"></i>&nbsp{{ post.user }}</p>
                <p><i id="icon" class="far fa-calendar-alt"></i> &nbsp{{ post.event_date.date }}</p>
                <p><i id="icon" class="fas fa-map-marker-alt"></i> &nbsp{{ post.location }}</p>
                <br>
                <strong>Details</strong>
                <p> {{ post.comment }} </p>
            </div>
                <div class="card" id="budget-card">
                    <div class="card-header">
                    <h5 id="budget-header">Budget</h5>
                    </div>
                    <div class="card-body">
                        <p id="budget">${{ post.budget }}</p>
                        <a href="{% url 'boards:create_bid' post_id=post.id %}">
                            {% if post.status != "OPEN" or post.user == user.username %}
                                <button id="bid-button" class="btn btn-success btn-sm" disabled>Create Bid</button>
                            {% else %}
                                <button id="bid-button" class="btn btn-success btn-sm">Create Bid</button>
                            {% endif %}
                        </a>
                    </div>
                </div>
        </div>
    </div>
</div>

<div class="card bg-light mt-3">
    <div class="container p-5">
        <h3 align="center" style="margin-bottom:30px">Current Bids</h3>
        {% for bid in post.bid_set.all %}
        <div class="card">
            <div class="card-header">
                <strong><i class="fas fa-user-circle"></i> {{ bid.user }} | ${{bid.price}}</strong>
                {% if post.status == "CLOSED" %}
                    {% if post.user == user.username %}
                        <form action="{% url 'boards:winner_selected' bid_id=bid.id %}">
                            {% if post.winner_selected == False %}
                                <button id="winner-selected-button" class="btn btn-success btn-sm" >Choose This Bidder</button>
                            {% endif %}
                        </form>
                    {% endif %}
                {% endif %}
            </div>
            <div class="card-body">
                <i class="fas fa-address-book"></i>
                <p class="card-text">{{ bid.contact_details }}</p>
                <i class="fas fa-comments"></i>
                <p class="card-text">{{ bid.comment }}</p>
            </div>
        </div>
        <br>
        {% endfor %}

    </div>
    {% endblock %}

templates/boards/index.html
{% extends "../base.html" %}
{% load crispy_forms_tags %}

{% block title %}
    Posts
{% endblock %}

{% block content %}

    <!-- Search bar -->
    <div class="search-container">
        <form type="get" action="{% url 'boards:search' %}" style="margin: 15px" class="form-inline">
            <input class="form-control mr-sm-2" type="search" placeholder="Search Postings..." aria-label="Search" id="search_box" name="search_box" style="width: 91%">
            <button class="btn btn-success" type="submit" id="search_submit">Search</button>
            <!-- <button type="submit" id="search_submit"><i class="fa fa-search"></i></button> -->
      </form>
    </div>

    <div class="container">
        <div class="row">
            <div class="col-3" style="padding-top: 16px">
                <form type="get" action=".">
                    <div class="card">
                        <header class="card-header" style="padding:5px">
                            <h6 class="title"><b>Sort By</b></h6>
                        </header>
                        <!-- sorting options -->
                        <div  style="padding: 20px" >
                            <form action="{% url 'boards:index' %}" method="post">
                                {% csrf_token %}
                                {{ form | crispy}}
                                <!-- {{ form | crispy }} -->
                                <input class="btn btn-success" type="submit" value="Apply" style="width: 80%; margin-left: 24px">
                            </form>
                        </div>
<!-- {#                        <article class="card-group-item">#}
{##}
{#                            <header class="card-header">#}
{#                                <h6 class="title">Sort By</h6>#}
{#                            </header>#}
{##}
{#                            <div class="filter-content">#}
{#                                <div class="card-body">#}
{#                                    <label class="form-check">#}
{#                                        <input class="form-check-input" type="checkbox" id="mostrecent">#}
{#                                        <span class="form-check-label">#}
{#      				                        Most Recent#}
{#      				                    </span>#}
{#                                    </label>#}
{##}
{#                                    <label class="form-check">#}
{#                                        <input class="form-check-input" type="checkbox" id="lowestBudget">#}
{#                                        <span class="form-check-label">#}
{#      				                        Lowest Budget#}
{#      				                    </span>#}
{#                                    </label>#}
{##}
{#                                    <label class="form-check">#}
{#                                        <input class="form-check-input" type="checkbox" id="highestbudget">#}
{#                                        <span class="form-check-label">#}
{#      				                        Highest Budget#}
{#      				                    </span>#}
{#                                    </label>#}
{##}
{#                                    <label class="form-check">#}
{#                                        <input class="form-check-input" type="checkbox" id="ascendingdate">#}
{#                                        <span class="form-check-label">#}
{#      				                        Event Date (Ascending)#}
{#      				                    </span>#}
{#                                    </label>#}
{##}
{#                                    <label class="form-check">#}
{#                                        <input class="form-check-input" type="checkbox" id="descendingdate">#}
{#                                        <span class="form-check-label">#}
{#      				                        Event Date (Descending)#}
{#      				                    </span>#}
{#                                    </label> #}
{#                                </div> #}
{#                            </div>#}
{#                        </article>#}
{##}
{#                        <article class="card-group-item">#}
{##}
{#                            <header class="card-header">#}
{#                                <h6 class="title">Filter By</h6>#}
{#                            </header>#}
{##}
{#                            <div class="filter-content">#}
{#                                <div class="card-body">#}
{#                                    <label class="form-check">#}
{#                                        Budget#}
{#                                        <div id="rangeBox">#}
{#                                            <div id="inputRange">#}
{#                                                <input type="number" step="1" min="0" max="1000" placeholder="Min" id="minBudget">#}
{#                                                <input type="number" step="1" min="0" max="1000" placeholder="Max" id="maxBudget">#}
{#                                            </div>#}
{#                                        </div>#}
{#                                    </label>#}
{##}
{#                                    <label class="form-check">#}
{#                                        <input class="form-check-input" type="checkbox" id="weekfilter">#}
{#                                        <span class="form-check-label">#}
{#                                            Next Week#}
{#                                        </span>#}
{#                                    </label>#}
{##}
{#                                    <label class="form-check">#}
{#                                        <input class="form-check-input" type="checkbox" id=monthfilter>#}
{#                                        <span class="form-check-label">#}
{#                                            Next Month#}
{#                                        </span>#}
{#                                    </label>#}
{##}
{#                                    <input id="search_submit" type="submit" value="submit">#}
{##}
{#                                    <a href="{% url 'boards:index' %}" class="btn btn-primary active" role="button"#}
{#                                       aria-pressed="true">Submit</a>#}
{##}
{#                                    <input class="btn btn-primary" type="submit" value="Submit">#}
{#                                </div> #}
{#                            </div>#}
{#                        </article> #}
{#                        #}-->
                    </div>
                </form>
            </div>

            <div class="col-9">
                {% if post_list %}
                    <div>
                        {% for post in post_list %}
                            <div class="card mt-3 mb-3">
                                <div class="card-header">
                                    <a href="{% url 'boards:detail' post.id %}" class="card-link" style="float: right">Details</a>
                                    <strong>{{ post.title }} | <span style="font-weight:normal" class="text-muted"> <i class="fas fa-user-circle"></i> {{ post.user }}</span></strong>
                                     <!-- <h6>{{ post.user }}</h6> -->
                                </div>
                                <div class="container">
                                    <p class="card-text" style="margin-top: 20px; margin-right: 15px; margin-left : 20px; margin-bottom: 0px">{{ post.comment }}</p>
                                  <div class="row">
                                    <div class="col">
                                        <div class="card-body">
                                            <p class="card-text"><i class="fas fa-dollar-sign" id="icon"></i>{{ post.budget }}</p>
                                            <p class="card-text">Closing on {{ post.end_date.date }}</p>
                                        </div>
                                    </div>
                                    <div class="col">
                                        <div class="card-body">
                                            <p class="card-text"><i id="icon"
                                                                    class="far fa-calendar-alt"></i> {{ post.event_date.date }}</p>
                                            <p class="card-text"><i id="icon"
                                                                    class="fas fa-map-marker-alt"></i> {{ post.location }}</p>
                                        </div>
                                    </div>
                                  </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                {% else %}
                    <p>No posts available</p>
                {% endif %}
        </div>
    </div>

{% endblock %}

templates/boards/my_bids.html
{% extends "../base.html" %}

{% block title %}
My Bids
{% endblock %}

{% block content %}

{% if bid_list %}
<h2 id="my-title">My Bids</h2>
<div>
    {% for bid in bid_list %}
    <div class="card mt-3 mb-3">
        <div class="card-header">
            <strong>{{bid.post.title}} | <span style="font-weight:normal" class="text-muted"> <i class="fas fa-user-circle"></i> {{ bid.post.user }}</span> |
                {% if bid.post.status == "OPEN" %}
                    <p id="status-open">{{ bid.post.status }}</p>
                {% elif bid.post.status == "CLOSED" %}
                    <p id="status-closed">{{ bid.post.status }}</p>
                {% elif bid.post.status == "ASSIGNED" %}
                    <p id="status-assigned">{{ bid.post.status }}</p>
                {% endif %}
            </strong>
            <a href="{% url 'boards:delete_bid' bid.id %}" class="card-link mr-2 text-danger" style="float: right">Delete</a>
            <a href="{% url 'boards:detail' bid.post.id %}" class="card-link mr-2" style="float: right">Details</a>
        </div>
        <div class="card-body">
            <div class="container">
                <p class="card-text">{{bid.post.comment}}</p>
              <div class="row">
                <div class="col">
                    <div class="card-body" style="padding: 5px">
                        <p class="card-text"><i id="icon" class="fas fa-dollar-sign"></i>{{ bid.post.budget }}</p>
                        <p class="card-text">Closing on {{bid.post.end_date.date }}</p>
                    </div>
                </div>
                <div class="col">
                    <div class="card-body">
                        <p class="card-text"><i id="icon"
                                                class="far fa-calendar-alt"></i> {{ bid.post.event_date.date }}</p>
                        <p class="card-text"><i id="icon"
                                                class="fas fa-map-marker-alt"></i> {{ bid.post.location }}</p>
                    </div>
                </div>
              </div>
            </div>
            <hr>
            <div class="card-body">
                <strong>My Bid | ${{bid.price}}</strong>
                <br>
                <br>
                <div class="row">
                <div class="col">
                    <div class="card-body" style="padding: 5px">
                        <p class="card-text"><i class="fas fa-address-book"></i> {{ bid.contact_details }}</p>
                        <p class="card-text"><i class="fas fa-comments"></i> {{ bid.comment }}</p>
                    </div>
                </div>
                {% if bid.post.winning_bid == bid.id %}
                    <div class="col">
                        <div class="card-body">
                            <p class="card-text">
                                <i class="fas fa-check"></i>
                                <strong id="bid-is-assigned"> You have been assigned this post.</strong>
                                <br>
                                The poster will notify you with more information.
                            </p>
                        </div>
                    </div>
                {% endif %}
              </div>

            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% else %}
<p>You have not bidded on any posts</p>
{% endif %}
{% endblock %}

templates/boards/my_posts.html
{% extends "../base.html" %}

{% block title %}
My Posts
{% endblock %}

{% block content %}

{% if post_list %}
<h2 id="my-title">My Posts</h2>
    {% for post in post_list %}
        <div class="card mt-3 mb-3">
            <div class="card-header">
                <strong>{{post.title}} |
                    {% if post.status == "OPEN" %}
                        <p id="status-open">{{ post.status }}</p>
                    {% elif post.status == "CLOSED" %}
                        <p id="status-closed">{{ post.status }}</p>
                    {% elif post.status == "ASSIGNED" %}
                        <p id="status-assigned">{{ post.status }}</p>
                    {% endif %}
                </strong>
                <a href="{% url 'boards:delete_post' post.id %}" class="card-link mr-2 text-danger" style="float: right">Delete</a>
                <a href="{% url 'boards:detail' post.id %}" class="card-link mr-2" style="float: right">Details</a>
            </div>
            <div class="container">
                <p class="card-text" style="margin-top: 20px; margin-right: 15px; margin-left : 20px; margin-bottom: 0px">{{ post.comment }}</p>
              <div class="row">
                <div class="col">
                    <div class="card-body">
                        <p class="card-text"><i class="fas fa-dollar-sign" id="icon"></i>{{ post.budget }}</p>
                        <p class="card-text">Closing on {{ post.end_date.date }}</p>
                    </div>
                </div>
                <div class="col">
                    <div class="card-body">
                        <p class="card-text"><i id="icon"
                                                class="far fa-calendar-alt"></i> {{ post.event_date.date }}</p>
                        <p class="card-text"><i id="icon"
                                                class="fas fa-map-marker-alt"></i> {{ post.location }}</p>
                    </div>
                </div>
              </div>
            </div>
        </div>
    {% endfor %}
{% else %}
<p>No posts available</p>
{% endif %}
{% endblock %}

templates/boards/new_bid_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
New Bid
{% endblock %}


{% block content %}
    <form method="post" action="{% url 'boards:create_bid' post_id=post_id %}">
        {{ form | crispy}}

        {% csrf_token %}
        <button type="submit" class="btn btn-success btn-sm">Create Bid</button>

    </form>
{% endblock %}

templates/boards/new_post_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
New Post
{% endblock %}


{% block content %}
    <form method="post" action="{% url 'boards:create_post' %}">
        {{ form | crispy}}

        {% csrf_token %}
        <button type="submit" class="btn btn-success btn-sm">Create Post</button>
    </form>
{%  endblock %}