boards/urls.py
from django.urls import path

from . import views

app_name = 'boards'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:post_id>/', views.detail, name='detail'),
    path('new_bid/<int:post_id>/', views.create_bid, name='create_bid'),
    path('new_post/', views.create_post, name='create_post'),
    path('my_posts/', views.my_posts, name='my_posts'),
    path('my_bids/', views.my_bids, name='my_bids'),
    path('winner_selected/<int:bid_id>/', views.set_winner_selected, name='winner_selected'),
    path('search/', views.search, name='search'),
    path('delete_post/<int:post_id>/', views.delete_post, name='delete_post'),
    path('delete_bid/<int:bid_id>/', views.delete_bid, name='delete_bid')
]

partywhip/urls.py
from django.contrib import admin
from django.contrib.auth.views import LogoutView, LoginView
from django.urls import path, include, re_path

from partywhip import views

urlpatterns = [
    path('', views.welcome, name="welcome"),
    path('admin/', admin.site.urls),
    path('boards/', include('boards.urls')),
    path('signup/', views.signup, name='signup'),
    path('login/', LoginView.as_view(template_name="partywhip/login_form.html"), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

templates/base.html
{% load staticfiles %}

<!doctype html>
<html class="no-js" lang="">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>{% block title %}{% endblock %}</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
        crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU"
        crossorigin="anonymous">
    <script src="{% static 'js/vendor/modernizr-2.8.3-respond-1.4.2.min.js' %}"></script>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top" id="navbar">
        <div class="container">
            <a class="navbar-brand" href="{% url 'welcome' %}">PartyWhip</a>
            <div class="navbar-nav">
                {% if user.is_authenticated %}
                    <a class="mr-2" href="{% url 'boards:create_post' %}">
                        <button class="btn btn-success">Create Post</button>
                    </a>
                    <a class="nav-item nav-link active" href="{% url 'boards:my_posts' %}">My Posts</a>
                    <a class="nav-item nav-link active" href="{% url 'boards:my_bids' %}">My Bids</a>
                    <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
                {% else %}
                    <a class="nav-item nav-link active" href="{% url 'login' %}">Login</a>
                    <a class="nav-item nav-link active" href="{% url 'signup' %}">Sign Up</a>
                {% endif %}
            </div>
        </div>
    </nav>

    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
</body>

</html>